version: '3.8'

services:
  chess-server:
    build: .
    container_name: chess-multiplayer
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped